from typing import Dict, Any, List
from datetime import datetime, timezone

class EmailRCAFormatter:
    """
    Formats rich HTML Root Cause Analysis (RCA) and Solution email reports for NOC Engineers.
    """
    @staticmethod
    def format_rca_email(triage_result: Dict[str, Any], recipient: str = "") -> Dict[str, str]:
        inc_id = triage_result.get("incident_id", "INC-001")
        probable_root = triage_result.get("probable_root", "Unknown Node")
        probable_root_node = triage_result.get("probable_root_node", "Unknown")
        probable_root_code = triage_result.get("probable_root_code", "UNKNOWN")
        severity = triage_result.get("severity", "CRITICAL")
        confidence = triage_result.get("confidence_score", 0.95) * 100
        rationale = triage_result.get("grouping_rationale", "")
        symptoms = triage_result.get("symptoms", [])
        checks = triage_result.get("cited_next_checks", [])
        draft_ticket = triage_result.get("draft_ticket", {})

        sev_color = "#d9534f" if severity == "CRITICAL" else ("#f0ad4e" if severity == "HIGH" else "#5bc0de")

        checks_html = ""
        for chk in checks:
            citation = chk.get("citation", "Runbook")
            content = chk.get("content", "")
            checks_html += f"""
            <div style="background-color: #f8f9fa; border-left: 4px solid #0275d8; padding: 10px; margin-bottom: 10px;">
                <strong>📌 Citation:</strong> <code>{citation}</code><br/>
                <p style="margin-top: 5px; color: #333;">{content}</p>
            </div>
            """

        symptoms_html = "".join([f"<li><code>{s}</code></li>" for s in symptoms[:8]])

        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ max-width: 680px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }}
                .header {{ background-color: #1a252f; color: #ffffff; padding: 20px; text-align: center; }}
                .badge {{ display: inline-block; padding: 6px 12px; background-color: {sev_color}; color: #fff; font-weight: bold; border-radius: 4px; }}
                .content {{ padding: 25px; }}
                .box {{ background-color: #f1f4f8; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
                .footer {{ background-color: #f8f9fa; text-align: center; padding: 15px; font-size: 12px; color: #777; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h2>📡 Network Incident Alert & RCA Report</h2>
                    <p style="margin:0;">Incident ID: {inc_id} | Time: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}</p>
                </div>
                <div class="content">
                    <div style="text-align: center; margin-bottom: 20px;">
                        <span class="badge">SEVERITY: {severity}</span>
                        <span style="font-weight:bold; margin-left: 15px;">Confidence: {confidence:.1f}%</span>
                    </div>

                    <div class="box">
                        <h3 style="margin-top:0; color: #d9534f;">🚨 Probable Root Cause Identified</h3>
                        <p style="font-size: 16px;"><strong>Root Node:</strong> <code>{probable_root_node}</code></p>
                        <p style="font-size: 16px;"><strong>Failure Code:</strong> <code>{probable_root_code}</code></p>
                        <p><strong>Description:</strong> {probable_root}</p>
                    </div>

                    <h3>📝 Grouping Rationale</h3>
                    <p>{rationale}</p>

                    <h3>📖 Cited Runbook Recommended Solutions</h3>
                    {checks_html if checks_html else "<p>No runbook citations found.</p>"}

                    <h3>🩺 Grouped Symptoms ({len(symptoms)})</h3>
                    <ul>
                        {symptoms_html}
                    </ul>

                    <div class="box" style="border-left: 4px solid #5cb85c;">
                        <h4 style="margin-top:0;">🎫 Auto-Generated Draft Ticket: {draft_ticket.get('ticket_id', 'TICK-001')}</h4>
                        <p><strong>Title:</strong> {draft_ticket.get('title', '')}</p>
                        <p><strong>Assignee:</strong> {draft_ticket.get('assignee', 'NOC Tier-2')}</p>
                    </div>
                </div>
                <div class="footer">
                    <p>Automated report generated by Network Health-Check & Alarm Triage Agent (PS06).</p>
                    <p>This alert is for information & validation. A human NOC engineer must confirm before network action.</p>
                </div>
            </div>
        </body>
        </html>
        """

        subject = f"[{severity} ALERT] Root Cause Identified for {inc_id}: {probable_root_node} ({probable_root_code})"
        
        return {
            "subject": subject,
            "html": html_content,
            "text": f"Incident {inc_id} Alert: Probable Root Cause {probable_root_node} ({probable_root_code}). Severity: {severity}."
        }
